name: Doxygen

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@v0.3
        with:
            required-ros-distributions: noetic

      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: *
          target-ros1-distro: noetic

      - shell: bash
        run: |
          ./smacc_ci/gh-pages.sh ${{ secrets.GITHUB_TOKEN }}
